package com.bobocode.svydovets.bibernate.constant;

public enum GenerationType {
    /**
     * Default behaviour of Id generation strategy, the whole process on ID management becomes user's
     * responsibility;
     */
    MANUAL,
    /**
     * Uses along with autogenerated database column value, doesn't require from user set the id
     * manually
     */
    IDENTITY,
    /**
     * Uses SEQUENCE table for getting id, takes the ID range specifying in allocationSize an is able
     * to take the id from the cache
     */
    SEQUENCE
}
