package com.bobocode.svydovets.bibernate.annotation;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Specifies the mapped column for a persistent property or field.
 * If no {@code Column} annotation is specified, the default values apply.
 */
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.FIELD)
public @interface Column {
    /**
     * The name of the column. Defaults to the property or field name.
     */
    String name() default "";

    /**
     * Whether the column is included in SQL INSERT statements generated by the persistence provider.
     */
    boolean insertable() default true;

    /**
     * Whether the column is included in SQL UPDATE statements generated by the persistence provider.
     */
    boolean updatable() default true;
}
